version: '3.8'
services:
  k6-load-test:
    build: .
    environment:
      VIRTUAL_USERS_CONSTANT: ${VIRTUAL_USERS_CONSTANT}
      VIRTUAL_USERS_RAMP_UP: ${VIRTUAL_USERS_RAMP_UP}
      VIRTUAL_USERS_RAMP_DOWN: ${VIRTUAL_USERS_RAMP_DOWN}
      TEST_DURATION_CONSTANT: ${TEST_DURATION_CONSTANT}
      TEST_DURATION_RAMP_UP: ${TEST_DURATION_RAMP_UP}
      TEST_DURATION_RAMP_DOWN: ${TEST_DURATION_RAMP_DOWN}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/loadTest.js"]

  k6-soak-test:
    build: .
    environment:
      BASE_URL: ${BASE_URL}
      STAGE1_DURATION: ${STAGE1_DURATION}
      STAGE1_TARGET: ${STAGE1_TARGET}
      STAGE2_DURATION: ${STAGE2_DURATION}
      STAGE2_TARGET: ${STAGE2_TARGET}
      STAGE3_DURATION: ${STAGE3_DURATION}
      STAGE3_TARGET: ${STAGE3_TARGET}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/soakTest.js"]

  k6-spike-test:
    build: .
    environment:
      SPIKE_VUS_HIGH: ${SPIKE_VUS_HIGH}
      SPIKE_VUS_LOW: ${SPIKE_VUS_LOW}
      SPIKE_DURATION_SHORT: ${SPIKE_DURATION_SHORT}
      SPIKE_DURATION_LONG: ${SPIKE_DURATION_LONG}
      SPIKE_RAMP_UP: ${SPIKE_RAMP_UP}
      SPIKE_RAMP_DOWN: ${SPIKE_RAMP_DOWN}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/spikeTest.js"]

  k6-stress-test:
    build: .
    environment:
      STRESS_VUS_LOW: ${STRESS_VUS_LOW}
      STRESS_VUS_MEDIUM: ${STRESS_VUS_MEDIUM}
      STRESS_VUS_HIGH: ${STRESS_VUS_HIGH}
      STRESS_VUS_MAX: ${STRESS_VUS_MAX}
      STRESS_DURATION_SHORT: ${STRESS_DURATION_SHORT}
      STRESS_DURATION_LONG: ${STRESS_DURATION_LONG}
      STRESS_RAMP_DOWN: ${STRESS_RAMP_DOWN}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/stressTest.js"]