version: '3.8'
services:
  k6-load-test:
    build: .
    environment:
      VIRTUAL_USERS_CONSTANT: ${VIRTUAL_USERS_CONSTANT}
      VIRTUAL_USERS_RAMP_UP: ${VIRTUAL_USERS_RAMP_UP}
      VIRTUAL_USERS_RAMP_DOWN: ${VIRTUAL_USERS_RAMP_DOWN}
      TEST_DURATION_CONSTANT: ${TEST_DURATION_CONSTANT}
      TEST_DURATION_RAMP_UP: ${TEST_DURATION_RAMP_UP}
      TEST_DURATION_RAMP_DOWN: ${TEST_DURATION_RAMP_DOWN}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./performance:/app/performance
      - ./debug:/app/debug
      - ./results:/app/performance/results  # Adicionado para persistir o relatório
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/loadTest.js -o html=/app/performance/results/index.html"]  # Modificado para gerar o relatório HTML