version: '3.8'
services:
  k6-load-test:
    build: .
    environment:
      VIRTUAL_USERS_CONSTANT: ${VIRTUAL_USERS_CONSTANT}
      VIRTUAL_USERS_RAMP_UP: ${VIRTUAL_USERS_RAMP_UP}
      VIRTUAL_USERS_RAMP_DOWN: ${VIRTUAL_USERS_RAMP_DOWN}
      TEST_DURATION_CONSTANT: ${TEST_DURATION_CONSTANT}
      TEST_DURATION_RAMP_UP: ${TEST_DURATION_RAMP_UP}
      TEST_DURATION_RAMP_DOWN: ${TEST_DURATION_RAMP_DOWN}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/loadTest.js"]

  k6-soak-test:
    build: .
    environment:
      BASE_URL: ${BASE_URL}
      STAGE1_DURATION: ${STAGE1_DURATION}
      STAGE1_TARGET: ${STAGE1_TARGET}
      STAGE2_DURATION: ${STAGE2_DURATION}
      STAGE2_TARGET: ${STAGE2_TARGET}
      STAGE3_DURATION: ${STAGE3_DURATION}
      STAGE3_TARGET: ${STAGE3_TARGET}
    volumes:
      - ./performance:/app/performance
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["k6 run /app/performance/soakTest.js"]