//  This file is for uploading the result file generated by cucumber to QTM4J   

var Client = require('node-rest-client').Client;
var client = new Client();
var fs = require("fs");
var dotenv = require('dotenv');
dotenv.config();

//set var type = Cloud or Server
const cucumberJsonDir = './cypress/test-results/merged-test-results.json'
var apiKey = process.env.APIKEY;
var summary = process.env.TESTCYCLE_SUMMARY;
var enviorment = process.env.BASEURL;
var build = process.env.BUILD;

// this code block will run when the type is set to 'Cloud'
var args = {
	data: {
		'format':"cucumber",
		'attachFile':true,
		'isZip':false,
		'environment':enviorment,
		'build':build,
		'fields':{
			'testCycle':{
				'status':"In Progress",
				'summary':summary,
				'description': summary,
				"labels":[
					"Cypress",
					"UI"
				],
			}
		}
	},
	headers: { "Content-Type": "application/json", "apiKey": apiKey,
	}
};

//1st API call
client.post('https://qtmcloud.qmetry.com/rest/api/automation/importresult', args, function(data, response) {
        
	//2nd API call
	client.put(data.url,{
		headers: { 'Content-Type': 'multipart/form-data' },
		data: fs.readFileSync(cucumberJsonDir, 'utf8', function(err, data) {
			if (err) throw err;
			console.log(data);
		})
	}, function optionalCallback(err, httpResponse, body) {
		if (err) {
			return console.error('upload failed:', err);
		}
		console.log('Upload successful! ');
	});
});
