name: K6 Load Test

on:
  workflow_dispatch:
    inputs:
      virtual_users_ramp_up:
        description: 'VUs em Ramp-Up'
        required: true
        default: '10'
      virtual_users_constant:
        description: 'VUs no tempo constante'
        required: true
        default: '10'
      virtual_users_ramp_down:
        description: 'VUs em Ramp-Down'
        required: true
        default: '0'
      test_duration_ramp_up:
        description: 'Tempo de Ramp-Up (ex: 5m)'
        required: true
        default: '5s'
      test_duration_constant:
        description: 'Tempo constante (ex: 20m)'
        required: true
        default: '10s'
      test_duration_ramp_down:
        description: 'Tempo de Ramp-Down (ex: 5m)'
        required: true
        default: '5s'
      base_url:
        description: 'Base URL para teste'
        required: true
        default: 'https://hml2.ilotto.com.br'

env:
  VIRTUAL_USERS_RAMP_UP: ${{ secrets.VIRTUAL_USERS_RAMP_UP }}
  VIRTUAL_USERS_CONSTANT: ${{ secrets.VIRTUAL_USERS_CONSTANT }}
  VIRTUAL_USERS_RAMP_DOWN: ${{ secrets.VIRTUAL_USERS_RAMP_DOWN }}
  TEST_DURATION_RAMP_UP: ${{ secrets.TEST_DURATION_RAMP_UP }}
  TEST_DURATION_CONSTANT: ${{ secrets.TEST_DURATION_CONSTANT }}
  TEST_DURATION_RAMP_DOWN: ${{ secrets.TEST_DURATION_RAMP_DOWN }}
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:k6io/k6
          sudo apt update
          sudo apt install -y k6

      - name: Set up environment variables
        run: |
          echo "VIRTUAL_USERS_RAMP_UP=${{ github.event.inputs.virtual_users_ramp_up }}" >> $GITHUB_ENV
          echo "VIRTUAL_USERS_CONSTANT=${{ github.event.inputs.virtual_users_constant }}" >> $GITHUB_ENV
          echo "VIRTUAL_USERS_RAMP_DOWN=${{ github.event.inputs.virtual_users_ramp_down }}" >> $GITHUB_ENV
          echo "TEST_DURATION_RAMP_UP=${{ github.event.inputs.test_duration_ramp_up }}" >> $GITHUB_ENV
          echo "TEST_DURATION_CONSTANT=${{ github.event.inputs.test_duration_constant }}" >> $GITHUB_ENV
          echo "TEST_DURATION_RAMP_DOWN=${{ github.event.inputs.test_duration_ramp_down }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ github.event.inputs.base_url }}" >> $GITHUB_ENV

      - name: Run K6 load test
        run: |
          docker-compose run --rm --user root k6-load-test sh
          cd performance/
          k6 run loadTest.js

      # - name: Run K6 load test
      #   run: docker-compose up --build

      - name: List performance directory
        run: ls -l performance/

      - name: List performance directory2
        run: ls -l ./

      - name: Upload K6 HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: K6 Load Test Report
          path: performance/index.html
