name: K6 Load Test

on:
  workflow_dispatch:
    inputs:
      virtual_users_ramp_up:
        description: 'VUs em Ramp-Up'
        required: true
        default: '10'
      virtual_users_constant:
        description: 'VUs no tempo constante'
        required: true
        default: '10'
      virtual_users_ramp_down:
        description: 'VUs em Ramp-Down'
        required: true
        default: '0'
      test_duration_ramp_up:
        description: 'Tempo de Ramp-Up (ex: 5m)'
        required: true
        default: '5s'
      test_duration_constant:
        description: 'Tempo constante (ex: 20m)'
        required: true
        default: '10s'
      test_duration_ramp_down:
        description: 'Tempo de Ramp-Down (ex: 5m)'
        required: true
        default: '5s'
      base_url:
        description: 'Base URL para teste'
        required: true
        default: 'https://hml2.ilotto.com.br'

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run K6 load test
        run: docker-compose up --build k6-load-test

      - name: List performance directory
        run: ls -l performance/

      - name: List performance directory2
        run: ls -l ./

      - name: Upload K6 HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: K6 Load Test Report
          path: performance/index.html
