name: K6 Spike Test

on:
  workflow_dispatch:
    inputs:
      request_type:
        type: choice
        description: 'Tipo de requisição (GET ou POST)'
        options:
          - GET
          - POST
      base_url:
        description: 'Base URL para teste'
        required: true
        default: 'https://api-hml.ilotto.com.br'
      post_body:
        description: 'Corpo da requisição POST (JSON)'
        required: false
        default: '{}'
      spike_vus_high:
        description: 'VUs em Spike'
        required: true
        default: '1400'
      spike_vus_low:
        description: 'VUs em estado normal'
        required: true
        default: '100'
      spike_duration_short:
        description: 'Duração curta do Spike'
        required: true
        default: '10s'
      spike_duration_long:
        description: 'Duração longa do Spike'
        required: true
        default: '3m'
      spike_ramp_up:
        description: 'Tempo de Ramp-Up'
        required: true
        default: '1s'
      spike_ramp_down:
        description: 'Tempo de Ramp-Down'
        required: true
        default: '10s'

env:
  SPIKE_VUS_HIGH: ${{ secrets.SPIKE_VUS_HIGH }}
  SPIKE_VUS_LOW: ${{ secrets.SPIKE_VUS_LOW }}
  SPIKE_DURATION_SHORT: ${{ secrets.SPIKE_DURATION_SHORT }}
  SPIKE_DURATION_LONG: ${{ secrets.SPIKE_DURATION_LONG }}
  SPIKE_RAMP_UP: ${{ secrets.SPIKE_RAMP_UP }}
  SPIKE_RAMP_DOWN: ${{ secrets.SPIKE_RAMP_DOWN }}
  BASE_URL: ${{ secrets.BASE_URL }}
  REQUEST_TYPE: ${{ secrets.REQUEST_TYPE }}

jobs:
  spike-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install k6
        run: |
          curl -sL https://github.com/grafana/k6/releases/download/v0.42.0/k6-v0.42.0-linux-amd64.deb -o k6.deb
          sudo dpkg -i k6.deb
          sudo apt-get install -f

      - name: Set up environment variables
        run: |
          echo "SPIKE_VUS_HIGH=${{ github.event.inputs.spike_vus_high }}" >> $GITHUB_ENV
          echo "SPIKE_VUS_LOW=${{ github.event.inputs.spike_vus_low }}" >> $GITHUB_ENV
          echo "SPIKE_DURATION_SHORT=${{ github.event.inputs.spike_duration_short }}" >> $GITHUB_ENV
          echo "SPIKE_DURATION_LONG=${{ github.event.inputs.spike_duration_long }}" >> $GITHUB_ENV
          echo "SPIKE_RAMP_UP=${{ github.event.inputs.spike_ramp_up }}" >> $GITHUB_ENV
          echo "SPIKE_RAMP_DOWN=${{ github.event.inputs.spike_ramp_down }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ github.event.inputs.base_url }}" >> $GITHUB_ENV
          echo "REQUEST_TYPE=${{ github.event.inputs.request_type }}" >> $GITHUB_ENV

      - name: Run K6 spike test
        run: |
          docker-compose run --rm --user root k6-spike-test sh
          mkdir -p performance/reports
          cd performance/
          echo '${{ inputs.post_body }}' > post_body.json
          k6 run spikeTest.js

      - name: Upload K6 HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: K6 Spike Test Report
          path: performance/reports/indexSpike.html

      - name: Publish Reports to Separate Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERFORMANCE_REPORTS_REPO_TOKEN }}
          external_repository: rodrigosalles7/performance-test-reports
          publish_dir: ./performance/reports
          destination_dir: spike-tests/reports
